default['ruby-env']['user'] = "ec2-user"
default['ruby-env']['group'] = "ec2-user"
default['ruby-env']['version'] = "2.4.1"
default['ruby-env']['rbenv_url'] = "https://github.com/sstephenson/rbenv.git"
default['ruby-env']['ruby-build_url'] = "https://github.com/sstephenson/ruby-build"
